### PR TITLE
Update dep versions

### LINKED ISSUE #8: Up to date versions?
Hello. I'm curious if this library is still in use - the versions of both Clojure and Datascript are behind. I try to trivial upgrade and hit errors...  before digging in, if it turns out there is an upgrade sitting out there that just hasn't been pushed yet, I would be pleased to obtain it. :-)

### PR DESCRIPTION
**Pull request by bahulneel**
This should resolve #8 and #9, but it would be nice if someone could independently verify it for me.

The mocha tests work (which is a start I guess) 😄

### CODE REVIEW

**Comment by ashnur** [comment]
Thanks, will check asap.

**Comment by bahulneel** [comment]
So far, have only found 1 issue.

It seems that from 0.18.0, transients were introduced as an optimisation. This means that the following now fails:
```
var db1 = d.empty_db();
var db2 = mori.toClj(db1);
assert(mori.equals(db1, db2));
```
With the error `Error: datascript.DB/conj! is not supported`

This may not be a massive issue moving forward, but good to know.

**Comment by ashnur** [comment]
Yeah, this is a problem.

**Comment by bahulneel** [comment]
Do you think we could lift the implementation from cljs.core, modify it and use that version to replace the mori version, like how I'm shimming datascript.core in?

**Comment by bahulneel** [comment]
so we can just implement `cljs.core/IEncodeClojure` and it's sorted.

**Comment by ashnur** [comment]
I am at work, but I will definitely review these and merge tonight. I am incredibly grateful @bahulneel that you help out with this, I need it but was not able to figure out how to do it.

**Comment by bahulneel** [comment]
No problem, we use it on a project here and it was starting to wind me up, especially considering we have closed issues on the main project that we couldn't use.

**Pull request merged**
